### PR TITLE
Selection_sort

### PR DESCRIPTION
**Pull request by Lordhermano**
With tests and log updated

### CODE REVIEW

**Comment by CollegePaul** [comment]
Thank you for this Mev, there are a couple of things to change before merging with the main branch:

The unsorted list is a reference to data, it is not a copy use data.copy() otherwise the original is modified.

Methods (functions) should not start with a capital letter

Some #comments are incomplete and stop in mid setence.

**Comment by CollegePaul** [comment]
Thanks for your submission, I am merging this in now, than you for all the work you put into this.

**Comment by Lordhermano** [comment]
Paul I need some help

**Comment by Lordhermano** [comment]
I left my purse in Richards room can you hold on to it

**Pull request merged**
